services:
  backend:
    build: ./backend
    container_name: food-restaurant-backend
    ports:
      - "5003:5003"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: food-restaurant-frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
